biblioteca

In [1]:
import pandas as pd

Dataframe de esportes

In [2]:
sport = {
    'modalidades': ['futebol', 'basquete', 'vôlei', 'natação'],
    'quantidade de atletas': [11, 5, 6, 8],
    'nomes_dos_times': ['time A', 'time B', 'time C', 'time D']

}

# Criando um DataFrame a partir do dicionário com os dados do sport
df = pd.DataFrame(sport)

# Exibibindo 
print(df)

  modalidades  quantidade de atletas nomes_dos_times
0     futebol                     11          time A
1    basquete                      5          time B
2       vôlei                      6          time C
3     natação                      8          time D

Transformando o conjunto de dados em csv com read

In [3]:
df.to_csv('sport.csv', index=False) # sanvando em csv o dataframe de sport

#@ Somete para informar que o arquivo CSV foi criado com sucesso
print ('Arquivo CSV criado com sucesso!')
# Lendo o arquivo CSV e exibindo seu conteúdo
df_csv = pd.read_csv('sport.csv')
print(df_csv)

Arquivo CSV criado com sucesso!
  modalidades  quantidade de atletas nomes_dos_times
0     futebol                     11          time A
1    basquete                      5          time B
2       vôlei                      6          time C
3     natação                      8          time D

Convertendo em excel

In [4]:
df.to_excel('sport.xlsx', index=False) # sanvando em excel o dataframe de sport

df_excel = pd.read_excel('sport.xlsx') # Lendo o arquivo Excel e exibindo seu conteúdo
df_excel

  modalidades  quantidade de atletas nomes_dos_times
0     futebol                     11          time A
1    basquete                      5          time B
2       vôlei                      6          time C
3     natação                      8          time D

Criando outro datasets para concatenar

In [5]:
jogadores = {
    'nomes_famosos': ['Pelé', 'Michael Jordan', 'Serena Williams', 'Usain Bolt'],
    'pais_de_origem': ['Brasil', 'Estados Unidos', 'Estados Unidos', 'Jamaica'],
}

df_jog = pd.DataFrame(jogadores)
df_jog

     nomes_famosos  pais_de_origem
0             Pelé          Brasil
1   Michael Jordan  Estados Unidos
2  Serena Williams  Estados Unidos
3       Usain Bolt         Jamaica

Concatenando

In [6]:
df_atualizado = pd.concat([df, df_jog], ignore_index=True)


# preencher os valores ausentes com 'Desconecido'
df_atualizado.fillna('falta preencher', inplace=True)
print(df_atualizado)

       modalidades quantidade de atletas  nomes_dos_times    nomes_famosos  \
0          futebol                  11.0           time A  falta preencher
1         basquete                   5.0           time B  falta preencher
2            vôlei                   6.0           time C  falta preencher
3          natação                   8.0           time D  falta preencher
4  falta preencher       falta preencher  falta preencher             Pelé
5  falta preencher       falta preencher  falta preencher   Michael Jordan
6  falta preencher       falta preencher  falta preencher  Serena Williams
7  falta preencher       falta preencher  falta preencher       Usain Bolt

    pais_de_origem
0  falta preencher
1  falta preencher
2  falta preencher
3  falta preencher
4           Brasil
5   Estados Unidos
6   Estados Unidos
7          Jamaica

/tmp/ipykernel_44053/437105203.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'falta preencher' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_atualizado.fillna('falta preencher', inplace=True)

json

In [7]:
#===========================================================================================

df_json = df_atualizado.to_json(orient='records') # Convertendo o DataFrame para JSON
df_json

'[{"modalidades":"futebol","quantidade de atletas":11.0,"nomes_dos_times":"time A","nomes_famosos":"falta preencher","pais_de_origem":"falta preencher"},{"modalidades":"basquete","quantidade de atletas":5.0,"nomes_dos_times":"time B","nomes_famosos":"falta preencher","pais_de_origem":"falta preencher"},{"modalidades":"v\\u00f4lei","quantidade de atletas":6.0,"nomes_dos_times":"time C","nomes_famosos":"falta preencher","pais_de_origem":"falta preencher"},{"modalidades":"nata\\u00e7\\u00e3o","quantidade de atletas":8.0,"nomes_dos_times":"time D","nomes_famosos":"falta preencher","pais_de_origem":"falta preencher"},{"modalidades":"falta preencher","quantidade de atletas":"falta preencher","nomes_dos_times":"falta preencher","nomes_famosos":"Pel\\u00e9","pais_de_origem":"Brasil"},{"modalidades":"falta preencher","quantidade de atletas":"falta preencher","nomes_dos_times":"falta preencher","nomes_famosos":"Michael Jordan","pais_de_origem":"Estados Unidos"},{"modalidades":"falta preencher","quantidade de atletas":"falta preencher","nomes_dos_times":"falta preencher","nomes_famosos":"Serena Williams","pais_de_origem":"Estados Unidos"},{"modalidades":"falta preencher","quantidade de atletas":"falta preencher","nomes_dos_times":"falta preencher","nomes_famosos":"Usain Bolt","pais_de_origem":"Jamaica"}]'

Inspecionando os dados

In [8]:
df_atualizado.head() # primeiros dados da tabela
#==========================================================================================
df_atualizado.tail() # ultimos dados
#==========================================================================================
df_atualizado.info() # informações sobre o dataframe
#==========================================================================================
df_atualizado.describe() # estatísticas do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   modalidades            8 non-null      object
 1   quantidade de atletas  8 non-null      object
 2   nomes_dos_times        8 non-null      object
 3   nomes_famosos          8 non-null      object
 4   pais_de_origem         8 non-null      object
dtypes: object(5)
memory usage: 452.0+ bytes

,modalidades,quantidade de atletas,nomes_dos_times,nomes_famosos,pais_de_origem
count,8,8,8,8,8
unique,5,5,5,5,4
top,falta preencher,falta preencher,falta preencher,falta preencher,falta preencher
freq,4,4,4,4,4

Fatiação de dados para se trabalha

In [9]:
# Fatiamento de dados
#==========================================================================================
df_atualizado['modalidades'] # selecionando a coluna 'modalidades'
#==========================================================================================
df_atualizado.loc[1] # selecionando a segunda linha do DataFrame
#==========================================================================================
df_atualizado.loc[1:3] # selecionando as segundas 3 linhas do DataFrame
#==========================================================================================
df_atualizado.loc[1:5, 'modalidades'] # selecionando as segundas 5 linhas da coluna 'modalidades'

1           basquete
2              vôlei
3            natação
4    falta preencher
5    falta preencher
Name: modalidades, dtype: object

In [10]:
df_filtando = df_atualizado['quantidade de atletas'] == "falta preencher" # criando um filtro para selecionar as linhas onde a quantidade de atletas é igual a "falta preencher"
df_filtrado = df_atualizado[df_filtando] # aplicando o filtro ao DataFrame
df_filtrado

,modalidades,quantidade de atletas,nomes_dos_times,nomes_famosos,pais_de_origem
4,falta preencher,falta preencher,falta preencher,Pelé,Brasil
5,falta preencher,falta preencher,falta preencher,Michael Jordan,Estados Unidos
6,falta preencher,falta preencher,falta preencher,Serena Williams,Estados Unidos
7,falta preencher,falta preencher,falta preencher,Usain Bolt,Jamaica

In [11]:
filtro2 = (df_atualizado['nomes_famosos'] == "Pelé") & (df_atualizado['pais_de_origem'] == "Brasil") # criando um filtro para selecionar as linhas onde os nomes famosos são iguais a "Pelé" e o país de origem é igual a "Brasil"
filtro2 = df_atualizado[filtro2] # aplicando o filtro ao DataFrame
filtro2

,modalidades,quantidade de atletas,nomes_dos_times,nomes_famosos,pais_de_origem
4,falta preencher,falta preencher,falta preencher,Pelé,Brasil

Grouby  e dropna e fillna

In [12]:
df_atualizado.fillna(value="falta preencher", inplace=True) # preenchendo os valores ausentes na coluna 'falta preencher' com o valor "falta preencher"

df_atualizado

,modalidades,quantidade de atletas,nomes_dos_times,nomes_famosos,pais_de_origem
0,futebol,11.0,time A,falta preencher,falta preencher
1,basquete,5.0,time B,falta preencher,falta preencher
2,vôlei,6.0,time C,falta preencher,falta preencher
3,natação,8.0,time D,falta preencher,falta preencher
4,falta preencher,falta preencher,falta preencher,Pelé,Brasil
5,falta preencher,falta preencher,falta preencher,Michael Jordan,Estados Unidos
6,falta preencher,falta preencher,falta preencher,Serena Williams,Estados Unidos
7,falta preencher,falta preencher,falta preencher,Usain Bolt,Jamaica